controller_manager:
  ros__parameters:
    update_rate: 30

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0

    open_loop: true

    base_frame_id: base_footprint
    odom_frame_id: odom

    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]

    enable_odom_tf: true

    wheels_per_side: 1
    wheel_separation: 0.186
    wheel_radius: 0.0325
